FROM oven/bun:1-slim as base
WORKDIR /app

FROM base AS prepare
RUN bun install -g turbo
COPY . .
RUN turbo prune web --docker

FROM base AS builder
ENV TURBO_TELEMETRY_DISABLED=1
COPY --from=prepare /app/out/json/ .
RUN bun install --ignore-scripts
COPY --from=prepare /app/out/full/ .
COPY --from=prepare /app/tsconfig.json .
RUN bun turbo build

FROM nginx:1.26.3-alpine3.20 AS runner
COPY ./apps/web/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/apps/web/dist /var/www/html/
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]