# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'
vars:
tasks:
  server:start:
    aliases: ['server:dev', 'server']
    desc: Starts docker containers, applies database migrations, and runs the development server
    cmds:
      - defer: docker compose stop db
      - docker compose up db -d
      - bun run --filter=server db:push
      - bun run dev:server
  test:all:
    aliases: ['test']
    desc: Runs all tests in the project
    cmds:
      - bun run test
  purge:all:
    aliases: ['purge']
    prompt: This will delete all node_modules, dist, and .turbo folders. Are you sure?
    desc: Removes all node_modules, .turbo, and dist folders in the project
    cmds:
      - find . -name "node_modules" -type d -prune -exec rm -rf {} +
      - find . -name "dist" -type d -prune -exec rm -rf {} +
      - find . -name ".turbo" -type d -prune -exec rm -rf {} +
